pipeline {
    agent any
    environment {
        DEPLOY_DIR = "deployment_ready"
    }
    stages {
        stage('Build') {
            steps {
                // Example for your Nuxt/Webapp
                dir('week2/webapp') {
                    sh 'npm install'
                    sh 'npm run build' 
                    sh "mkdir -p ../../${DEPLOY_DIR}"
                    sh "cp -r .output/* ../../${DEPLOY_DIR}/"
                }
            }
        }
        stage('Package') {
            steps {
                // Using the native Linux zip command
                sh "zip -r deployment.zip ${DEPLOY_DIR}"
            }
        }
    }
    post {
        success {
            archiveArtifacts artifacts: 'deployment.zip'
        }
    }
}
