server {
    #  listen on HTTP port 80
    listen 80;

    #  Identify the domain name we defined in /etc/hosts
    server_name webapp.local ;

    #  Tell Nginx where your HTML/CSS files are actually stored
    root /home/anonymous/assignment/week2/webapp/.output/public;

    #  Set the default file to serve
    index index.html;

   

    #  Handle the 404 requirement
    error_page 404 /404.html;

    #  Set up the separate logging files required by Task 2
    access_log /var/log/nginx/webapp_access.log;
    error_log /var/log/nginx/webapp_error.log;

    location / {
        # Check if file exists, if not, throw 404
        try_files $uri $uri/ =404;
    }
    
    
}
